export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS'

export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const CLEAR_COUNTER = 'CLEAR_COUNTER'
